<link rel="stylesheet" href="css/details_tc_mobile.css"/>
<?php require('header.html') ?>
<?php require('header-tc-nav.html') ?>
	<div class="details">
		<div class="details-sta-one details-page">
			<div class="sta-one-cen white">
				<h1>主要数据</h1>
				<ul>
					<li>
					<label>
						<span>车色选择</span>
					</label>
					<label>
						<span>前倾角</span>
					</label>
					</li>
					<li>
					<label>
						<span>复古绿／卡其黄／深海蓝／亮钻黑</span>
					</label>
					<label>
						<span>25° </span>
					</label>
					</li>
					<li>
					<label>
						<span>尺寸规格</span>
					</label>
					<label>
						<span>转向角度</span>
					</label>
					</li>
					<li>
					<label>
						<span>1926X710X1100mm</span>
					</label>
					<label>
						<span>40°</span>
					</label>
					</li>
					<li>
					<label>
						<span>轴距</span>
					</label>
					<label>
						<span>最小离地间隙</span>
					</label>
					</li>
					<li>
					<label>
						<span>1305mm</span>
					</label>
					<label>
						<span>198mm</span>
					</label>
					</li>
					<li>
					<label>
						<span></span>
					</label>
					<label>
						<span>坐垫高度</span>
					</label>
					</li>
					<li>
					<label>
						<span></span>
					</label>
					<label>
						<span>776mm</span>
					</label>
					</li>
				</ul>
			</div>
		</div>
		<div class="details-sta-two details-page">
			 <img src="images/tc/standard/san_02.jpg" >
			 <div class="sta-two-top">
			 	<h1>电驱系统</h1>
			 	<ul>
			 	<li>
			 		<label>电池类型</label>
			 		18650锂电
			 	</li>
			 	<li>
			 		<label>电芯品牌</label>
			 		松下／三星／LG
			 	</li>
			 	<li>
			 		<label>电压</label>
			 		60V
			 	</li>
			 	<li>
			 		<label>容量</label>
			 		30Ah
			 	</li>
			 	
			 	<li>
			 		<label>标准充电电流</label>
			 		4A
			 	</li>
			 	<li>
			 		<label>电机</label>
			 		BOSCH电机
			 	</li>
			 	<li>
			 		<label>电机控制方式</label>
			 		矢量控制
			 	</li>
			 	
			 	<li>
			 		<label>电机额定功率</label>
			 		1500w
			 	</li>
			 	<li>
			 		<label>电机扭矩</label>
			 		150N·m
			 	</li>
			 	<li>
			 		<label>控制器限制电流</label>
			 		40A
			 	</li>
			 	<li>
			 		<label>三挡限速</label>
			 		19/40/60
			 	</li>
			 	<li>
			 		<label>仪表</label>
			 		LCD液晶仪表
			 	</li>
			 	<li>
			 		<label>仪表颜色</label>
			 		白色背光
			 	</li>
			 	<li>
			 		<label>仪表亮度自动调节</label>
			 	</li>
			 	</ul>
			 </div>	
		</div>
		<div class="details-sta-three details-page">
			 <img src="images/tc/standard/san_03.jpg" >
			 	<div class="sta-two-top">
			 	<h1>性能参数</h1>
			 	<ul>
			 	<li>
			 		<label>续航里程</label>100KM
			 	</li>
			 		<li>
			 		<label>爬坡能力</label>17° 
			 	</li>
			 		<li>
			 		<label>额定最大载重量</label>150KG
			 	</li>
			 		<li>
			 		<label>制动系统</label>CBS前后联动
			 	</li>
			 		<li>
			 		<label>前制动方式</label>240mm单碟，双缸活塞卡钳
			 	</li>
			 		<li>
			 		 <label>后制动方式</label>180mm单碟，单缸活塞卡钳
			 	</li>
			 		<li>
			 		<label>干态制动距离</label>﹤1.3（20km/h）
			 	</li>
			 		<li>
			 		<label>前悬挂系统</label>35mm倒立液压减震
			 	</li>
			 		<li>
			 		<label>前悬挂总行程</label>110mm
			 	</li>
                <li>
			 		<label>后悬挂系统</label>中置液压减震
			 	</li>
			 		<li>
			 		<label>后悬挂总行程</label>30mm
			 	</li>	
			 	<li>
			 		<label>前轮</label>8辐铝制轻量化轮毂MT2.15-17
			 	</li>
			 		<li>
			 		<label>前轮胎规格</label>90/80-17
			 	</li>
			 		<li>
			 		<label>后轮</label>8辐铝制轻量化轮毂MT3.0-17
			 	</li>
			 	<li>
			 		<label>后轮胎规格</label>110/70-17
			 	</li>
			 </div>
		</div>
		<div class="details-sta-four details-page">
			 <img src="images/tc/standard/san_04.jpg" >
			 	<div class="sta-two-top">
			 	<h1>车辆配置</h1>
			 	<ul>
			 	<li>
			 		<small>智能光敏感应系统</small>
			 		<small>LED制动灯</small>
			 		<small>智能遥控器</small>
			 	</li>
			 	<li>
			 		<small>LED前大灯</small>
			 		<small>前大灯效果</small>
			 		<small>车内直充/电池单充</small>	 		
			 	</li>
			 	<li>
			 		<small>LED后尾灯</small>
			 		<small>一键启动</small>
			 		<small>电子边撑</small>
			 	</li>
			 	<li>
			 		<small>LED转向灯</small>
			 		<small>后乘员脚踏</small>
			 		<small>防盗报警器</small>
			 	</li>
			 	</ul>
               </div>
		</div>
	</div>
<?php require('footer.html') ?>	
 <script type="text/javascript">
 	$(function(){
 	 	$("#index").html(getStorage("index6").split(",")[0]);
 	 	$("#tc-btn").html(getStorage("index6").split(",")[1])
 	})
 </script>